import * as p from '@clack/prompts';
import { writeFileSync } from 'fs';
import { CURATED_PACKAGES, ROLE_PRESETS } from '../data/packages.js';

export async function runSetup(): Promise<void> {
  p.intro('aztec-watch setup');

  // Step 1: Role
  const role = await p.select({
    message: 'What are you building?',
    options: Object.keys(ROLE_PRESETS).map(r => ({ value: r, label: r })),
  });
  if (p.isCancel(role)) { p.cancel('Setup cancelled.'); process.exit(0); }

  const preselected = new Set(ROLE_PRESETS[role as string]);

  // Step 2: Review packages
  const wantsReview = await p.confirm({
    message: `${preselected.size} packages pre-selected for "${role as string}". Review and customize?`,
    initialValue: false,
  });
  if (p.isCancel(wantsReview)) { p.cancel('Setup cancelled.'); process.exit(0); }

  let selectedPackages: string[];

  if (wantsReview) {
    const result = await p.multiselect({
      message: 'Select packages to monitor  (↑↓ move · space toggle · a toggle all · enter confirm)',
      options: CURATED_PACKAGES.map(pkg => ({
        value: pkg.name,
        label: pkg.name,
        hint: `${pkg.category} — ${pkg.purpose}`,
      })),
      initialValues: [...preselected],
      required: true,
    });
    if (p.isCancel(result)) { p.cancel('Setup cancelled.'); process.exit(0); }
    selectedPackages = result as string[];
  } else {
    selectedPackages = [...preselected];
  }

  // Step 3: Notification channel
  const wantsSlack = await p.confirm({
    message: 'Send notifications to Slack?',
    initialValue: true,
  });
  if (p.isCancel(wantsSlack)) { p.cancel('Setup cancelled.'); process.exit(0); }

  let slackLine = '';

  if (wantsSlack) {
    const url = await p.text({
      message: 'Slack webhook URL',
      placeholder: 'https://hooks.slack.com/services/...',
      validate: v => v.startsWith('https://hooks.slack.com/') ? undefined : 'Must be a valid Slack webhook URL',
    });
    if (p.isCancel(url)) { p.cancel('Setup cancelled.'); process.exit(0); }

    // Store value in env, not in config file
    process.env['SLACK_WEBHOOK_URL'] = url as string;
    slackLine = `  slack:\n    webhook_url: \${SLACK_WEBHOOK_URL}`;
    p.log.info('SLACK_WEBHOOK_URL saved to env for this session.\nFor GitHub Actions: add it as a repository secret named SLACK_WEBHOOK_URL');
  }

  // Generate config YAML
  const notifyBlock = slackLine;
  const yaml = generateConfig(selectedPackages, notifyBlock);

  writeFileSync('aztec-watch.config.yaml', yaml, 'utf8');

  p.outro(
    `Config saved to aztec-watch.config.yaml\n` +
    `  Watching: ${selectedPackages.length} packages\n` +
    `  Notifications: ${wantsSlack ? 'slack' : 'none (dry run)'}\n\n` +
    `Next steps:\n` +
    `  Run once now:     npx tsx src/cli/index.ts run\n` +
    `  GitHub Actions:   copy .github/workflows/watch.yml to your repo`
  );
}

function generateConfig(packages: string[], notifyBlock: string): string {
  const pkgLines = packages
    .map(name => {
      const pkg = CURATED_PACKAGES.find(p => p.name === name);
      const tags = pkg?.tags.slice(0, 2) ?? ['latest']; // default to first 2 tags
      const schnorr = name === '@aztec/accounts' ? '\n    check_schnorr_class_id: true' : '';
      return `  - name: "${name}"\n    tags: [${tags.join(', ')}]${schnorr}`;
    })
    .join('\n');

  const lines = [
    '# Generated by aztec-watch setup',
    `packages:\n${pkgLines}`,
    notifyBlock ? `notify:\n${notifyBlock}` : '# notify: (none configured — dry run)',
    'digest_window_seconds: 300',
    'db_path: data/state.db',
  ];

  return lines.join('\n\n') + '\n';
}
