import * as p from '@clack/prompts';
import { writeFileSync, existsSync } from 'fs';
import { CURATED_PACKAGES, CATEGORIES, ROLE_PRESETS } from '../data/packages.js';

export async function runSetup(): Promise<void> {
  console.log('');

  p.intro('aztec-watch');

  // ── Step 1: Role ─────────────────────────────────────────────────────────

  const role = await p.select({
    message: 'What are you building?',
    options: [
      { value: 'dApp / frontend',    label: 'dApp / frontend',    hint: 'aztec.js, accounts, wallets, pxe' },
      { value: 'Smart contract',     label: 'Smart contract',     hint: 'aztec.js, noir-contracts, simulator' },
      { value: 'Wallet integration', label: 'Wallet integration', hint: 'accounts, wallets, wallet-sdk, pxe' },
      { value: 'Node / validator',   label: 'Node / validator',   hint: 'aztec-node, sequencer, validator, p2p' },
      { value: 'Faucet / tooling',   label: 'Faucet / tooling',   hint: 'aztec.js, accounts, cli, builder' },
    ],
  });
  if (p.isCancel(role)) { p.cancel('Cancelled.'); process.exit(0); }

  const preselected = new Set(ROLE_PRESETS[role as string]);

  // ── Step 2: Review packages ───────────────────────────────────────────────

  const wantsReview = await p.confirm({
    message: `${preselected.size} packages pre-selected. Customize?`,
    initialValue: false,
  });
  if (p.isCancel(wantsReview)) { p.cancel('Cancelled.'); process.exit(0); }

  let selectedPackages: string[];

  if (wantsReview) {
    // Build grouped options: { "Core SDK": [...], "Infrastructure": [...], ... }
    const grouped: Record<string, { value: string; label: string; hint: string }[]> = {};
    for (const cat of CATEGORIES) {
      grouped[cat] = CURATED_PACKAGES
        .filter(pkg => pkg.category === cat)
        .map(pkg => ({
          value: pkg.name,
          label: pkg.name,
          hint: pkg.purpose,
        }));
    }

    const result = await p.groupMultiselect({
      message: 'Select packages to monitor',
      options: grouped,
      initialValues: [...preselected],
      required: true,
    });
    if (p.isCancel(result)) { p.cancel('Cancelled.'); process.exit(0); }
    selectedPackages = result as string[];
  } else {
    selectedPackages = [...preselected];
  }

  // ── Step 3: Slack webhook ─────────────────────────────────────────────────

  const url = await p.text({
    message: 'Slack incoming webhook URL',
    placeholder: 'https://hooks.slack.com/services/...',
    validate: v => {
      if (!v) return 'Paste your Slack webhook URL';
      if (!v.startsWith('https://hooks.slack.com/')) return 'Must start with https://hooks.slack.com/';
    },
  });
  if (p.isCancel(url)) { p.cancel('Cancelled.'); process.exit(0); }

  // ── Write config ──────────────────────────────────────────────────────────

  const yaml = generateConfig(selectedPackages);
  writeFileSync('aztec-watch.config.yaml', yaml, 'utf8');

  // ── Done ──────────────────────────────────────────────────────────────────

  const hasWorkflow =
    existsSync('.github/workflows/watch.yml') ||
    existsSync('.github/workflows/aztec-watch.yml');

  if (hasWorkflow) {
    p.note(
      `git add aztec-watch.config.yaml\n` +
      `git commit -m "configure aztec-watch"\n` +
      `git push`,
      'Commit your config'
    );

    p.note(
      `Repo → Settings → Secrets → Actions → New secret\n` +
      `Name:  SLACK_WEBHOOK_URL\n` +
      `Value: (your webhook URL)`,
      'Add the GitHub secret'
    );

    p.outro(`Watching ${selectedPackages.length} packages. Notifications go to Slack every 15 min.`);
  } else {
    p.note(
      `export SLACK_WEBHOOK_URL="${url as string}"\n` +
      `npm run build && node dist/cli/index.js run`,
      'Run locally'
    );

    p.outro(`Config saved. ${selectedPackages.length} packages configured.`);
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────

function generateConfig(packages: string[]): string {
  const pkgLines = packages
    .map(name => {
      const pkg = CURATED_PACKAGES.find(p => p.name === name);
      const tags = pkg?.tags.slice(0, 2) ?? ['latest'];
      const schnorr = name === '@aztec/accounts' ? '\n    check_schnorr_class_id: true' : '';
      return `  - name: "${name}"\n    tags: [${tags.join(', ')}]${schnorr}`;
    })
    .join('\n');

  return [
    '# aztec-watch config — generated by `aztec-watch init`',
    `packages:\n${pkgLines}`,
    'notify:\n  slack:\n    webhook_url: ${SLACK_WEBHOOK_URL}',
    'digest_window_seconds: 300',
    'state_path: data/state.json',
  ].join('\n\n') + '\n';
}
